name: run go-ovirt-client tests manually
on:
  workflow_dispatch:
    inputs:
      is_live:
        description: 'Live or Mock'
        default: 'live'
        required: true

jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: self-hosted
    steps:
    - name: Send greeting
      run: echo "Running  tests in ${{ github.event.inputs.is_live }} env"
    - name: Print github workspace
      run: |
        echo "GITHUB_WORKSPACE = $GITHUB_WORKSPACE"
        echo "github.workspace = ${{ github.workspace }}"
        echo "pr.ref = ${{github.event.pull_request.head.ref}}"
        echo "github.ref = ${{ github.ref }}"
        echo "$GITHUB_CONTEXT"
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}      
    - uses: actions/checkout@v2
      with:
        path: ${{ github.ref }}
        clean: true
    - name: trigger the ost tests
      run: |
        ls -latr
        cd ost-podman/
        timeout 40 make run-ost-engine-ui     
