name: run go-ovirt-client tests manually
on:
  workflow_dispatch:
    inputs:
      is_live:
        description: 'Live or Mock'
        default: 'live'
        required: true

jobs:
  # This workflow contains a single job called "greet"
  run-ost:
    # The type of runner that the job will run on
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
      with:
        clean: true
    - name: trigger the ost tests
      run: |
        timeout 40 sudo make run-ost-engine-ui     

    
  cleanup:
    runs-on: self-hosted
    needs: [run-ost]
    if: always()
    steps:
    - name: cleanup
      run: |
        timeout 40 sudo make cleanup