name: run go-ovirt-client tests manually
on:
  workflow_dispatch:
    inputs:
      is_live:
        description: 'Live or Mock'
        default: 'live'
        required: true

jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: self-hosted
    steps:
    - name: Send greeting
      run: echo "Running  tests in ${{ github.event.inputs.is_live }} env"
    - name: trigger the job
      run: timeout 40 /work/test-go-ovirt.sh live
